name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [created, published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run check

      - name: Build project
        run: npm run build

      - name: Create build artifact archive
        run: |
          cd dist
          tar -czf ../react-ui-dist.tar.gz .
          cd ..
          zip -r react-ui-dist.zip dist/

      - name: Get release info
        id: release_info
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "upload_url=${{ github.event.release.upload_url }}" >> $GITHUB_OUTPUT
            echo "tag_name=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release (if triggered by tag)
        id: create_release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_info.outputs.tag_name }}
          release_name: Release ${{ steps.release_info.outputs.tag_name }}
          draft: false
          prerelease: false
          body: |
            ## Build Artifacts
            
            - `react-ui-dist.tar.gz` - Production build (recommended)
            - `react-ui-dist.zip` - Production build (zip format)
            
            ## Usage
            
            Download and extract to your Nginx directory:
            
            ```bash
            wget https://github.com/${{ github.repository }}/releases/download/${{ steps.release_info.outputs.tag_name }}/react-ui-dist.tar.gz
            tar -xzf react-ui-dist.tar.gz -C /var/www/react-ui
            ```

      - name: Upload tar.gz to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || github.event.release.upload_url }}
          asset_path: ./react-ui-dist.tar.gz
          asset_name: react-ui-dist.tar.gz
          asset_content_type: application/gzip

      - name: Upload zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url || github.event.release.upload_url }}
          asset_path: ./react-ui-dist.zip
          asset_name: react-ui-dist.zip
          asset_content_type: application/zip
